apiVersion: v1
kind: Service
metadata:
  name: ai-platform-service
  labels:
    app: ai-platform-api
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: ai-platform-api
